title: My Blog
description: A blog about things
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://to3b.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-tactile
